### ISSUE TITLE
Study Real Python articles

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#132]
# Intermediate

- [ ] [Getting Started With Async Features in Python](https://realpython.com/python-async-features/)
- [ ] [Context Managers and Python's with Statement](https://realpython.com/python-with-statement/)
- [ ] [How to Use Generators and yield in Python](https://realpython.com/introduction-to-python-generators/)
- [ ] [Python's assert: Debug and Test Your Code Like a Pro](https://realpython.com/python-assert-statement/)
- [ ] [Python Descriptors: An Introduction](https://realpython.com/python-descriptors/)
- [ ] [The Python pickle Module: How to Persist Objects in Python](https://realpython.com/python-pickle-module/)
- [ ] [What Are Python Wheels and Why Should You Care?](https://realpython.com/python-wheels/)
- [ ] [Object-Oriented Programming (OOP) in Python 3](https://realpython.com/python3-object-oriented-programming/)
- [ ] [Write Pythonic and Clean Code With namedtuple](https://realpython.com/python-namedtuple/)
- [ ] [Recursion in Python: An Introduction](https://realpython.com/python-recursion/)
- [ ] [Brython: Python in Your Browser](https://realpython.com/brython-python-in-browser/)
- [ ] [Functional Programming in Python: When and How to Use It](https://realpython.com/python-functional-programming/)
- [ ] [Pipenv: A Guide to the New Python Packaging Tool](https://realpython.com/pipenv-guide/)
- [ ] [Python Debugging With Pdb](https://realpython.com/python-debugging-pdb/)
- [ ] [Python's Instance, Class, and Static Methods Demystified](https://realpython.com/instance-class-and-static-methods-demystified/)
- [ ] [Python Virtual Environments: A Primer](https://realpython.com/python-virtual-environments-a-primer/)
- [ ] [How to Round Numbers in Python](https://realpython.com/python-rounding/)
- [ ] [How to Iterate Through a Dictionary in Python](https://realpython.com/iterate-through-dictionary-python/)
- [ ] [An Intro to Threading in Python](https://realpython.com/intro-to-python-threading/)
- [ ] [Supercharge Your Classes With Python super()](https://realpython.com/python-super/)
- [ ] [Jupyter Notebook: An Introduction](https://realpython.com/jupyter-notebook-introduction/)
- [ ] [Python Type Checking (Guide)](https://realpython.com/python-type-checking/)
- [ ] [Memory Management in Python](https://realpython.com/python-memory-management/)
- [ ] [Pointers in Python: What's the Point?](https://realpython.com/pointers-in-python/)
- [ ] [Inheritance and Composition: A Python OOP Guide](https://realpython.com/inheritance-composition-python/)
