### ISSUE TITLE
Study Python's async I/O programming

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#134]
# Description

- [ ] [Real Python: Async IO in Python: A Complete Walkthrough](https://realpython.com/async-io-python/) which mentions other articles:
  - [ ] [How the heck does async/await work in Python 3.5?](https://snarky.ca/how-the-heck-does-async-await-work-in-python-3-5/)
  - [ ] [Cooperative Multitasking with Coroutines](https://pymotw.com/3/asyncio/coroutines.html)
  - [ ] [A Curious Course on Coroutines and Concurrency](http://www.dabeaz.com/coroutines/)
  - [ ] [John Reese - Thinking Outside the GIL with AsyncIO and Multiprocessing - PyCon 2018](https://youtu.be/0kXaLh8Fz3k)
  - [ ] [Some thoughts on asynchronous API design in a post-async/await world](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/)
  - [ ] [curio](https://github.com/dabeaz/curio): Curio is a coroutine-based library for concurrent Python systems programming using async/await.
  - [ ] [Trio](https://github.com/python-trio/trio): A friendly Python library for async concurrency and I/O.
  - [ ] [The State of Python Coroutines: yield from](https://www.andy-pearce.com/blog/posts/2016/Jun/the-state-of-python-coroutines-yield-from/)
  - [ ] [I don’t understand Python’s Asyncio](http://lucumr.pocoo.org/2016/10/30/i-dont-understand-asyncio/)
  - [ ] [series on asyncio](http://www.artificialworlds.net/blog/2017/05/31/basic-ideas-of-python-3-asyncio-concurrency/) (4 posts)
  - [ ] [AsyncIO for the Working Python Developer](https://hackernoon.com/asyncio-for-the-working-python-developer-5c468e6e2e8e)
  - [ ] [Asyncio Coroutine Patterns: Beyond await](https://medium.com/python-pandemonium/asyncio-coroutine-patterns-beyond-await-a6121486656f)
