### ISSUE TITLE
Read Working Draft, Standard for Programming Language C++

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#154]
Read [Working Draft, Standard for Programming Language C++](https://eel.is/c++draft/):

- [ ] 1 Scope[[intro.scope]](https://eel.is/c++draft/intro.scope)
- [ ] 2 Normative references[[intro.refs]](https://eel.is/c++draft/intro.refs)
- [ ] 3 Terms and definitions[[intro.defs]](https://eel.is/c++draft/intro.defs)
- [ ] 4 General principles[[intro]](https://eel.is/c++draft/#intro)
- [ ] 5 Lexical conventions[[lex]](https://eel.is/c++draft/#lex)
- [ ] 6 Basics[[basic]](https://eel.is/c++draft/#basic)
- [ ] 7 Expressions[[expr]](https://eel.is/c++draft/#expr)
- [ ] 8 Statements[[stmt.stmt]](https://eel.is/c++draft/#stmt.stmt)
- [ ] 9 Declarations[[dcl.dcl]](https://eel.is/c++draft/#dcl.dcl)
- [ ] 10 Modules[[module]](https://eel.is/c++draft/#module)
- [ ] 11 Classes[[class]](https://eel.is/c++draft/#class)
- [ ] 12 Overloading[[over]](https://eel.is/c++draft/#over)
- [ ] 13 Templates[[temp]](https://eel.is/c++draft/#temp)
- [ ] 14 Exception handling[[except]](https://eel.is/c++draft/#except)
- [ ] 15 Preprocessing directives[[cpp]](https://eel.is/c++draft/#cpp)
- [ ] 16 Library introduction[[library]](https://eel.is/c++draft/#library)
- [ ] 17 Language support library[[support]](https://eel.is/c++draft/#support)
- [ ] 18 Concepts library[[concepts]](https://eel.is/c++draft/#concepts)
- [ ] 19 Diagnostics library[[diagnostics]](https://eel.is/c++draft/#diagnostics)
- [ ] 20 Memory management library[[mem]](https://eel.is/c++draft/#mem)
- [ ] 21 Metaprogramming library[[meta]](https://eel.is/c++draft/#meta)
- [ ] 22 General utilities library[[utilities]](https://eel.is/c++draft/#utilities)
- [ ] 23 Strings library[[strings]](https://eel.is/c++draft/#strings)
- [ ] 24 Containers library[[containers]](https://eel.is/c++draft/#containers)
- [ ] 25 Iterators library[[iterators]](https://eel.is/c++draft/#iterators)
- [ ] 26 Ranges library[[ranges]](https://eel.is/c++draft/#ranges)
- [ ] 27 Algorithms library[[algorithms]](https://eel.is/c++draft/#algorithms)
- [ ] 28 Numerics library[[numerics]](https://eel.is/c++draft/#numerics)
- [ ] 29 Time library[[time]](https://eel.is/c++draft/#time)
- [ ] 30 Localization library[[localization]](https://eel.is/c++draft/#localization)
- [ ] 31 Input/output library[[input.output]](https://eel.is/c++draft/#input.output)
- [ ] 32 Regular expressions library[[re]](https://eel.is/c++draft/#re)
- [ ] 33 Concurrency support library[[thread]](https://eel.is/c++draft/#thread)
- [ ] Annex A (informative)
- [ ] Grammar summary[[gram]](https://eel.is/c++draft/#gram)
- [ ] Annex B (normative)
- [ ] Implementation quantities[[implimits]](https://eel.is/c++draft/implimits)
- [ ] Annex C (informative)
- [ ] Compatibility[[diff]](https://eel.is/c++draft/#diff)
- [ ] Annex D (normative)
- [ ] Compatibility features[[depr]](https://eel.is/c++draft/#depr)
- [ ] Annex E (informative)
- [ ] Conformance with UAX #31[[uaxid]](https://eel.is/c++draft/#uaxid)
- [ ] [Bibliography](https://eel.is/c++draft/bibliography)
- [ ] [Index](https://eel.is/c++draft/generalindex)
- [ ] [Index of grammar productions](https://eel.is/c++draft/grammarindex)
- [ ] [Index of library headers](https://eel.is/c++draft/headerindex)
- [ ] [Index of library names](https://eel.is/c++draft/libraryindex)
- [ ] [Index of library concepts](https://eel.is/c++draft/conceptindex)
- [ ] [Index of implementation-defined behavior](https://eel.is/c++draft/impldefindex)
