### ISSUE TITLE
Study Linear Algebra Done Right

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#155]
_Linear Algebra Done Right_
- [ ] 1 Vector Spaces
  - [ ] 1.A Rn and Cn
    - [ ] Complex Numbers
    - [ ] Lists
    - [ ] Fn
    - [ ] Digression on Fields
    - [ ] Exercises 1.A
  - [ ] 1.B Definition of Vector Space
    - [ ] Exercises 1.B 17
  - [ ] 1.C Subspaces
    - [ ] Sums of Subspaces 20
    - [ ] Direct Sums 21
    - [ ] Exercises 1.C 24

(To be continued)

**Comment by yaobinwen** [comment]
# Extended Reading

- [ ] [Flatland: A Romance of Many Dimensions by Edwin Abbott Abbott](https://www.gutenberg.org/ebooks/201)
