### ISSUE TITLE
Learn basics of LaTeX

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#156]
The purpose of this task is not to learn everything about LaTeX but to learn just enough to start a LaTeX document so I can keep my notes. Once I can create this document, I will keep learning LaTeX as needed.

[Learn LaTeX in 30 minutes](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes):
- [x] 1 What is LaTeX?
- [x] 2 Why learn LaTeX?
- [x] 3 Writing your first piece of LaTeX
- [x] 4 The preamble of a document
- [x] 5 Including title, author and date information
- [x] 6 Adding comments
- [x] 7 Bold, italics and underlining
- [x] 8 Adding images
  - [x] 8.1 Captions, labels and references
- [x] 9 Creating lists in LaTeX
  - [x] 9.1 Unordered lists
  - [x] 9.2 Ordered lists
- [x] 10 Adding math to LaTeX
  - [x] 10.1 Inline math mode
  - [x] 10.2 Display math mode
  - [x] 10.3 More complete examples
- [x] 11 Basic document structure
  - [x] 11.1 Abstracts
  - [x] 11.2 Paragraphs and new lines
  - [x] 11.3 Chapters and sections
- [x] 12 Creating tables
  - [x] 12.1 Creating a basic table in LaTeX
  - [x] 12.2 Adding borders
  - [x] 12.3 Captions, labels and references
- [x] 13 Adding a Table of Contents
- [x] 14 Downloading your finished document
- [x] 15 Finding and using LaTeX packages
  - [x] 15.1 Loading packages
  - [x] 15.2 Finding information about packages: CTAN
  - [x] 15.3 Packages available on Overleaf: Introducing TeX Live
