### ISSUE TITLE
Figure out why `nc` allows two instances to listen to the same `address:port`

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#177]
# Description

On my machine:
- `nc -v -l 127.0.0.1 8888` can succeed.
- On the same machine, running `nc -v -l 127.0.0.1 8888` again can still succeed.

But I remember TCP doesn't allow listening to the same address/port at the same time. What's going on?

# TODO

- [x] https://stackoverflow.com/questions/1694144/can-two-applications-listen-to-the-same-port
- [x] https://stackoverflow.com/questions/37570647/how-netcat-can-listen-to-the-same-port-on-the-same-host-from-two-different-termi
- [x] How to resolve the `undefined reference res_init`?

**Comment by yaobinwen** [comment]
# Update (2023-07-10)

So [this answer](https://stackoverflow.com/a/55731510/630364) tells why:

> So the socket is setup with the options `SO_REUSEADDR` and `SO_REUSEPORT`, which allow multiple processes to bind to the same port and same listening address. ... The goal of this option is to allow an easy form of **load balancing**: incoming connections to the port will be redirected to one of the processes (apparently at random).

This answer also recommends the detailed answer [here](https://stackoverflow.com/a/14388707/630364). But this detailed answer provides so much information that I need to study further in another session.
