### ISSUE TITLE
Study MIT OCW 18.100A Real Analysis

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#189]
# Description

- [x] Introduction
  - [x] 0.1 About this book
  - [x] 0.2 About analysis
  - [x] 0.3 Basic set theory
  - [x] Exercises
- [ ] 1. Real Numbers
  - [ ] 1.1 Basic properties
  - [ ] 1.2 The set of real numbers
  - [ ] 1.3 Absolute value and bounded functions
  - [ ] 1.4 Intervals and the size of R
  - [ ] 1.5 Decimal representation of the reals
  - [ ] Exercises
- [ ] (More to come)
