### ISSUE TITLE
Go through Stanford: CS103: Mathematical Foundations of Computing

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#194]
# Description

- [ ] [CS103: Mathematical Foundations of Computing](https://web.stanford.edu/class/cs103/)
  - [ ] The lecture slides can be found [here](https://web.stanford.edu/class/cs103/lectures/). The class is still going on as of 2023-07-20.
  - [ ] [Introduction, Set Theory](https://web.stanford.edu/class/cs103/lectures/00/)
  - [ ] [Mathematical Proofs](https://web.stanford.edu/class/cs103/lectures/01/)
  - [ ] [Indirect Proofs](https://web.stanford.edu/class/cs103/lectures/02/)
  - [ ] [Propositional Logic](https://web.stanford.edu/class/cs103/lectures/03/)
  - [ ] [First-Order Logic, Part I](https://web.stanford.edu/class/cs103/lectures/04/)
  - [ ] [First-Order Logic, Part II](https://web.stanford.edu/class/cs103/lectures/05/)
  - [ ] [Functions, Part I](https://web.stanford.edu/class/cs103/lectures/06/)
  - [ ] [Functions, Part II](https://web.stanford.edu/class/cs103/lectures/07/)
  - [ ] [Graphs, Part I](https://web.stanford.edu/class/cs103/lectures/08/)
  - [ ] [Graphs, Part II](https://web.stanford.edu/class/cs103/lectures/09/)
  - [ ] [Mathematical Induction, Part I](https://web.stanford.edu/class/cs103/lectures/10/)
  - [ ] etc.

**Comment by yaobinwen** [comment]
# Update (2023-07-20)

I wanted to study propositional logic because I want to evaluate [the following proof](https://www.quora.com/How-do-I-prove-that-A-B-C-A-B-A-C) (see the reply by [Jan Hidders](https://www.quora.com/profile/Jan-Hidders)):

```
To show this we need to show that for any x the following two statements are equivalent:

    x∈A∖(B∩C)

x∈(A∖B)∪(A∖C)

We can show this by using the definitions of the set operations and propositional reasoning rules:

(i) x∈A∖(B∩C)

By definition of ∖

this is equivalent to:

(ii) x∈A∧x∉(B∩C)

By definition of ∩

this is equivalent to:

(iii) x∈A∧¬(x∈B∧x∈C))

By De Morgan (i.e. ¬(P∧Q)
is equivalent to ¬P∨¬Q

) this is equivalent to:

(iv) x∈A∧(x∉B∨x∉C)

By distribution of ∧
over ∨

this is equivalent to:

(v) (x∈A∧x∉B)∨(x∈A∧x∉C)

By definition of ∖

this is equivalent to:

(vi) x∈A∖B∨x∈A∖C

By definition of ∪

this is equivalent to:

(vii) x∈(A∖B)∪(A∖C)

QED
```
