### ISSUE TITLE
Study Stanford CS107: Computer Organization & Systems

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#202]
# Description

- [ ] [CS107: Computer Organization & Systems](https://web.stanford.edu/class/archive/cs/cs107/cs107.1238/):
  - [ ] Lecture 01: Welcome to CS107!
  - [ ] Lecture 02: Integer Representations and Bits / Bytes
  - [ ] Lecture 03: Bits, Bytes, and Bitwise Operators
  - [ ] Lecture 04: Chars and C-Strings
  - [ ] Lecture 05: C-Strings, Pointers, and Arrays 
  - [ ] Lecture 06: Arrays and Pointers
  - [ ] Lecture 07: The Stack & Heap
  - [ ] Lecture 08: Generics and `void *`
  - [ ] Lecture 09: Function Pointers
  - [ ] Lecture 10: Intro to `x86-64`, Data Movement
  - [ ] Lecture 11: `x86-64` ALU
  - [ ] Lecture 12: `x86-64` Condition Codes and Control Flow
  - [ ] Lecture 13: `x86-64` Assembly Continued
  - [ ] Lecture 14: Assembly & Optimization
  - [ ] Lecture 15: Accessing the Architecture: An Introduction to Computer Architecture
