### ISSUE TITLE
Chatper 3: The NASM Language

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#214]
# TODOs

- [x] Section 3.1: Layout of a NASM Source Line
- [x] Section 3.2: Pseudo-Instructions
    - [x] Section 3.2.1: Dx: Declaring Initialized Data
    - [x] Section 3.2.2: RESB and Friends: Declaring Uninitialized Data
    - [x] Section 3.2.3: INCBIN: Including External Binary Files
    - [x] Section 3.2.4: EQU: Defining Constants
    - [x] Section 3.2.5: TIMES: Repeating Instructions or Data
- [x] Section 3.3: Effective Addresses
- [x] Section 3.4: Constants
    - [x] Section 3.4.1: Numeric Constants
    - [x] Section 3.4.2: Character Strings
    - [x] Section 3.4.3: Character Constants
    - [x] Section 3.4.4: String Constants
    - [x] Section 3.4.5: Unicode Strings
    - [x] Section 3.4.6: Floating-Point Constants
    - [x] Section 3.4.7: Packed BCD Constants
- [x] Section 3.5: Expressions
    - [x] Section 3.5.1: ? ... :: Conditional Operator
    - [x] Section 3.5.2: : ||: Boolean OR Operator
    - [x] Section 3.5.3: : ^^: Boolean XOR Operator
    - [x] Section 3.5.4: : &&: Boolean AND Operator
    - [x] Section 3.5.5: : Comparison Operators
    - [x] Section 3.5.6: |: Bitwise OR Operator
    - [x] Section 3.5.7: ^: Bitwise XOR Operator
    - [x] Section 3.5.8: &: Bitwise AND Operator
    - [x] Section 3.5.9: Bit Shift Operators
    - [x] Section 3.5.10: + and -: Addition and Subtraction Operators
    - [x] Section 3.5.11: Multiplication, Division and Modulo
    - [x] Section 3.5.12: Unary Operators
- [x] Section 3.6: SEG and WRT
- [x] Section 3.7: STRICT: Inhibiting Optimization
- [x] Section 3.8: Critical Expressions
- [x] Section 3.9: Local Labels
