### ISSUE TITLE
Learn Assembly Language

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#217]
# Description

[NASM Assembly Language Tutorials - asmtutor.com](https://asmtutor.com):
- [x] Lesson 1 Hello, world!
- [x] Lesson 2 Proper program exit
- [x] Lesson 3 Calculate string length
- [x] Lesson 4 Subroutines
- [x] Lesson 5 External include files
- [x] Lesson 6 NULL terminating bytes
- [x] Lesson 7 Linefeeds
  - [x] Why can't I call `sprint` and immediately followed by `sprint_lf`?
- [x] Lesson 8 Passing arguments
- [x] Lesson 9 User input
- [x] Lesson 10 Count to 10
- [x] Lesson 11 Count to 10 (itoa)
- [x] Lesson 12 Calculator - addition
- [x] Lesson 13 Calculator - subtraction
- [x] Lesson 14 Calculator - multiplication
- [x] Lesson 15 Calculator - division
- [x] Lesson 16 Calculator (atoi)
- [x] Lesson 17 Namespace
- [x] Lesson 18 Fizz Buzz
- [x] Lesson 19 Execute Command
- [x] Lesson 20 Process Forking
- [x] Lesson 21 Telling the time
- [x] Lesson 22 File Handling - Create
- [x] Lesson 23 File Handling - Write
- [x] Lesson 24 File Handling - Open
- [x] Lesson 25 File Handling - Read
- [x] Lesson 26 File Handling - Close
- [x] Lesson 27 File Handling - Update
- [x] Lesson 28 File Handling - Delete
- [x] Lesson 29 Sockets - Create
- [x] Lesson 30 Sockets - Bind
- [x] Lesson 31 Sockets - Listen
- [x] Lesson 32 Sockets - Accept
- [x] Lesson 33 Sockets - Read
- [x] Lesson 34 Sockets - Write
- [x] Lesson 35 Sockets - Close
- [x] Lesson 36 Download a Webpage

**Comment by yaobinwen** [comment]
# Update (2023-09-04)

This tutorial is good in the aspect of paving easy steps for beginners: in every lesson the talks a little bit more but not too much. The only thing that this tutorial fails to do is to talk about the "programming environment" that can give the readers the "big picture" about assembly programming.
