### ISSUE TITLE
Chapter 4: Entering 32-bit Protected Mode

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#220]
# TODOs

- [x] 4.1 Adapting to Life Without BIOS
- [x] 4.2 Understanding the Global Descriptor Table
- [x] 4.3 Defining the GDT in Assembly
- [x] 4.4 Making the Switch
- [x] 4.5 Putting it all Together
