### ISSUE TITLE
Chapter 5: Writing, Building, and Loading Your Kernel

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#221]
# TODOs

- [x] 5.1 Understanding C Compilation
  - [x] 5.1.1 Generating Raw Machine Code
  - [x] 5.1.2 Local Variables
  - [x] 5.1.3 Calling Functions
  - [x] 5.1.4 Pointers, Addresses, and Data
- [x] 5.2 Executing our Kernel Code
  - [x] 5.2.1 Writing our Kernel
  - [x] 5.2.2 Creating a Boot Sector to Bootstrap our Kernel
  - [x] 5.2.3 Finding Our Way into the Kernel
- [x] 5.3 Automating Builds with Make
  - [x] 5.3.1 Organising Our Operating System’s Code Base
- [x] 5.4 C Primer
  - [x] 5.4.1 The Pre-processor and Directives
  - [x] 5.4.2 Function Declarations and Header Files
