### ISSUE TITLE
Tech dash: GitHub REST API; GitHub App; GitHub access token

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#222]
# TODOs

- [ ] [GitHub Access Tokens explained](https://devopsjournal.io/blog/2022/01/03/GitHub-Tokens)
- [ ] [GitHub REST API: Pulls](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28)
- [ ] [Tool: tryapis](https://tryapis.com/github/api/repos-list-pull-requests-associated-with-commit)
- [ ] [Differences between GitHub Apps and OAuth apps](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/differences-between-github-apps-and-oauth-apps)

**Comment by yaobinwen** [comment]
# Notes

> If you want to use the API on behalf of an organization or another user, GitHub recommends that you use a GitHub App.

> If you want to use the API in a GitHub Actions workflow, GitHub recommends that you authenticate with the built-in GITHUB_TOKEN instead of creating a token.
