### ISSUE TITLE
Read book: IPv6 Fundamentals: A Straightforward Approach to Understanding IPv6 (2nd edition)

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#224]
- [ ] Part I Introduction to IPv6
  - [ ] Chapter 1 Introduction to IPv6
  - [ ] Chapter 2 IPv6 Primer
  - [ ] Chapter 3 Comparing IPv4 and IPv6
- [ ] Part II IPv6 Addresses
  - [ ] Chapter 4 IPv6 Address Representation and Address Types
  - [ ] Chapter 5 Global Unicast Address
  - [ ] Chapter 6 Link-Local Unicast Address
  - [ ] Chapter 7 Multicast Addresses
- [ ] Part III Dynamic IPv6 Addressing
  - [ ] Chapter 8 Basics of Dynamic Addressing in IPv6
  - [ ] Chapter 9 Stateless Address Autoconfiguration (SLAAC)
  - [ ] Chapter 10 Stateless DHCPv6
  - [ ] Chapter 11 Stateful DHCPv6
- [ ] Part IV ICMPv6 and ICMPv6 Neighbor Discovery
  - [ ] Chapter 12 ICMPv6
  - [ ] Chapter 13 ICMPv6 Neighbor Discovery
- [ ] Part V Routing IPv6
  - [ ] Chapter 14 IPv6 Routing Table and Static Routes
  - [ ] Chapter 15 EIGRP for IPv6
  - [ ] Chapter 16 OSPFv3
- [ ] Part VI Implementing IPv6
  - [ ] Chapter 17 Deploying IPv6 in the Network
