### ISSUE TITLE
Developing Essential Device Drivers and a Filesystem

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#237]
# TODOs

- [x] 6.1 Hardware Input/Output
  - [x] 6.1.1 I/O Buses
  - [x] 6.1.2 I/O Programming
    - [x] Figure out how to use the address `0x3F2` and the example assembly code.
  - [x] 6.1.3 Direct Memory Access
- [x] 6.2 Screen Driver
  - [x] 6.2.1 Understanding the Display Device
  - [x] 6.2.2 Basic Screen Driver Implementation
  - [x] 6.2.3 Scrolling the Screen
- [x] 6.3 Handling Interrupts
- [x] 6.4 Keyboard Driver
- [x] 6.5 Hard-disk Driver
- [x] 6.6 File System
