### ISSUE TITLE
Study Emory University CS 255 and CS 355 (first half)

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#241]
# TODOs

- [x] [CS255 Syllabus & Progress](http://www.cs.emory.edu/~cheung/Courses/255/Syllabus/syl.html)
  - [x] 30. Prelude to assembler programming: internal details of the CPU
    - [x] The structure of the Central Processing Unit (CPU)
      - [x] How the CPU uses the general purpose registers
      - [x] How the CPU uses the special purpose registers (Program flow)
    - [x] The Instruction Execution Cycle of the CPU
      - [x] Instruction Execution Cycle - in order program flow
      - [x] Instruction Execution Cycle - out-of-order program flow (branching)
  - [x] Intro to assembler programming using the ARM processor
    - [x] A historical introduction to programming languages
    - [x] Prelude to assembler programming - get to know your CPU !!!
    - [x] The ARM processor's CPU architecture:
      - [x] The registers of the ARM processor
      - [x] EGTAPI's display of the registers
    - [x] The "Hello World" program in assembler programming language
    - [x] Program organization illustrated using the "Hello World" assembler program with the help of EGTAPI
    - [x] Labels in Assembler Programming
- [x] [CS355 Syllabus & Progress](http://www.cs.emory.edu/~cheung/Courses/355/Syllabus/syl-2023.html)
  - [x] 1. Logic elements and Boolean Algebra
  - [x] 2. Switching Circuits... how the CPU transports values from one place to another...
    - [x] Filtering property of the AND gate
    - [x] Collating property of the OR gates
    - [x] Multiplexor circuit - the many-to-one digital switching circuit
    - [x] Defining your own components in EDiSim
    - [x] Using multiplexors to switch registers to ALU's input
    - [x] One-from-many digital selection circuit - the decoder
    - [x] Using decoder to select a register for writing
    - [x] Register → ALU → Register transfer
    - [x] Enrichment material: Demultiplexor - the one-to-many switching circuit
  - [x] 3. Arithmetic (and Logic) Circuits.... see what the ALU look like
    - [x] Intro to arithmetic circuits (circuits that perform computations)
    - [x] The "ripple-carry" adder using "full" adder circuits
    - [x] Array notation in EDiSim
    - [x] The subtract circuit
    - [x] The multiply circuit: Assign project 2 to re-inforce arithmetic circuit
    - [x] Postscript - what about more complex functions like sin(x)
    - [x] Finally, I can now show you what the ALU look like: ---- a simplified ALU slides
    - [x] Shifter:
  - [x] 4. Sequential Circuits
    - [x] Introduction
    - [x] The SR-latch
    - [x] 1-bit-memory and register
    - [x] Circuit timing and D-flipflops
  - [x] 5. Finite State Machines
    - [x] Constructing FSA with digital circuitry
  - [x] 6. Bi-directional Transfer
    - [x] Review of the rules to connect (digital) circuit components
    - [x] From tri-state-buffer to a bi-directional bus
    - [x] A more efficient way to multiplex registers to the ALU input (using tri-state-buffers)
  - [x] 7. Memory Organization
    - [x] Structure of a computer memory made with D-latches/Dff's
    - [x] Building larger memories
  - [x] 8. CPU Architecture: data path
    - [x] Introduction
    - [x] The various data forwarding paths within the simple datapath
    - [x] Controlling the datapath
    - [x] Controlling the ordering of events/actions in the datapath.
  - [x] 9. How the CPU communicate with (reads/writes) the memory - the system bus and its bus protocol:
    - [x] Introduction
    - [x] Closer look at the CPU
    - [x] Computer buses
    - [x] Asynchronous Buses
    - [x] Synchronous Buses
    - [x] Bus Arbitration
    - [x] M68000 data sheet (for background info only - not part of syllabus)
