### ISSUE TITLE
Learn Simple CPU Design

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#244]
- [ ] Learn Simple CPU Design
  - [ ] SimpleCPU version 1: trust me CPUs are simple: a simple 8bit RISCy CPU
  - [ ] SimpleCPU versions 1a/b/c: new, improved and optimised ...
  - [ ] SimpleCPU version 1a - back to basics: implementing a simulator in CPUSim
  - [ ] SimpleCPU version 1a - bread boarded: simpleCPU v1a implemented on bread board
  - [ ] SimpleCPU version 1a - python assembler: you can only write so much machine code before you write an assembler :)
  - [ ] SimpleCPU version 1a - fpga: simpleCPU v1a implemented on FPGA (redrawn)
  - [ ] SimpleCPU version 1a - serial IO : an updated hello-world bit-banged serial IO example.
  - [ ] SimpleCPU version 1a - TTL: simpleCPU v1a implemented in TTL.
  - [ ] SimpleCPU version 1a - datasheet: a quick reference guide of its architecture and instruction set.
  - [ ] SimpleCPU version 1a1 - fpga: simpleCPU v1a1 how to add new instructions.
  - [ ] SimpleCPU version 1d - fpga: an improved simpleCPU, more memory, more instructions, more addressing modes.
  - [ ] SimpleCPU version 1d - images: what do you need from your HW / SW to process an image?
  - [ ] SimpleCPU version 1d - pong: the beginning, turning the SimpleCPU into a games console.
  - [ ] SimpleCPU version 1d - datasheet: a quick reference guide of its architecture and instruction set.
  - [ ] SimpleCPU version 1d1 - interrupts: improving functionality, adding interrupt support
  - [ ] SimpleCPU version 1d1 - clock: how to implement an interrupt driven clock
  - [ ] SimpleCPU version 1d - space invaders: finally, getting closer to building a games console :)
  - [ ] SimpleCPU version 1d - game of life: the classic zero player game
  - [ ] SimpleCPU version 1e - fpga: what changes do we need to make to support a data stack?
  - [ ] SimpleCPU version 1e - datasheet: a quick reference guide of its architecture and instruction set.
  - [ ] Game Controllers: to play a game you need a game controller.
  - [ ] Video Game Console: version 1 of the simpleCPU games console.
  - [ ] SimpleCPU version 2: trust me again CPUs are simple: a simple 8bit CISCy CPU
  - [ ] SimpleCPU version 3: a simple CPU optimised for simple image processing, what could be simpler :)
  - [ ] SimpleCPU version 4: a pipelined version of the SimpleCPU.
