### ISSUE TITLE
Read: TCP/IP Tutorial and Technical Overview

### ISSUE THREAD

**Issue by yaobinwen** [yaobinwen/robin_on_rails#44]
[TCP/IP Tutorial and Technical Overview](http://www.redbooks.ibm.com/abstracts/gg243376.html)

- [ ] Part 1. Core TCP/IP protocols
  - [ ] Chapter 1. Architecture, history, standards, and trends
  - [ ] Chapter 2. Network interfaces
  - [ ] Chapter 3. Internetworking protocols
  - [ ] Chapter 4. Transport layer protocols
  - [ ] Chapter 5. Routing protocols
  - [ ] Chapter 6. IP multicast
  - [ ] Chapter 7. Mobile IP
  - [ ] Chapter 8. Quality of service
  - [ ] Chapter 9. IP version 6
  - [ ] Chapter 10. Wireless IP

- [ ] Part 2. TCP/IP application protocols
  - [ ] Chapter 11. Application structure and programming interfaces
  - [ ] Chapter 12. Directory and naming protocols
  - [ ] Chapter 13. Remote execution and distributed computing
  - [ ] Chapter 14. File-related protocols
  - [ ] Chapter 15. Mail applications
  - [ ] Chapter 16. The Web
  - [ ] Chapter 17. Network management
  - [ ] Chapter 18. Wireless Application Protocol
  - [ ] Chapter 19. Presence over IP

- [ ] Part 3. Advanced concepts and new technologies
  - [ ] Chapter 20. Voice over Internet Protocol
  - [ ] Chapter 21. Internet Protocol Television
  - [ ] Chapter 22. TCP/IP security
  - [ ] Chapter 23. Port based network access control
  - [ ] Chapter 24. Availability, scalability, and load balancing

- [ ] Appendix A. Multiprotocol Label Switching

**Comment by yaobinwen** [comment]
**TODO**: Need to study the [TCP Finite State Machine](http://tcpipguide.com/free/t_TCPOperationalOverviewandtheTCPFiniteStateMachineF-2.htm) to understand how states transition from one to another.

**Comment by yaobinwen** [comment]
**TODO**: I haven't fully understood the TCP congestion control algorithms in Section 4.4.3. Will need to come back sometime later.
